---
language: c
  #
notifications:
  email: true
  #
before_install:
  #
  # Fetch the tag information for the current branch
  - git fetch origin --tags
  #
  # Publish the buildroot script folder
  - chmod +x ${TRAVIS_BUILD_DIR}/buildroot/bin/*
  - ln -s ${TRAVIS_BUILD_DIR}/buildroot/bin/ ~/bin
  #
  # Start fb X server
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16"
  - sleep 3
  - export DISPLAY=:1.0
  #
install:
  #
  # Install arduino 1.6.10
  - wget http://downloads-02.arduino.cc/arduino-1.6.10-linux64.tar.xz
  - tar xf arduino-1.6.10-linux64.tar.xz
  - sudo mv arduino-1.6.10 /usr/local/share/arduino
  - ln -s /usr/local/share/arduino/arduino ${TRAVIS_BUILD_DIR}/buildroot/bin/arduino
  #
  # Install: LiquidCrystal_I2C library
  - git clone https://github.com/kiyoshigawa/LiquidCrystal_I2C.git
  - mv LiquidCrystal_I2C/LiquidCrystal_I2C /usr/local/share/arduino/libraries/LiquidCrystal_I2C
  #
  # Install: LiquidTWI2 library
  - git clone https://github.com/lincomatic/LiquidTWI2.git
  - sudo mv LiquidTWI2 /usr/local/share/arduino/libraries/LiquidTWI2
  #
  # Install: Monochrome Graphics Library for LCDs and OLEDs
  - git clone https://github.com/olikraus/U8glib_Arduino.git
  - sudo mv U8glib_Arduino /usr/local/share/arduino/libraries/U8glib
  #
  # Install: L6470 Stepper Motor Driver library
  - git clone https://github.com/ameyer/Arduino-L6470.git
  - sudo mv Arduino-L6470/L6470 /usr/local/share/arduino/libraries/L6470
  #
  # Install: TMC26X Stepper Motor Controller library
  - git clone https://github.com/trinamic/TMC26XStepper.git
  - sudo mv TMC26XStepper /usr/local/share/arduino/libraries/TMC26XStepper
  #
before_script:
  #
  # Change current working directory to the build dir
  - cd ${TRAVIS_BUILD_DIR}
  
script:
  #
  # Backup Configuration.h, Configuration_adv.h, and pins_RAMPS.h
  #
  - cp Marlin/Configuration.h Marlin/Configuration.h.backup
  - cp Marlin/Configuration_adv.h Marlin/Configuration_adv.h.backup
  - cp Marlin/pins_RAMPS.h Marlin/pins_RAMPS.h.backup
  #
  # Build with the default configurations in debug
  #
  - opt_enable _DEBUG
  - build_marlin
  
  #
  # Test build with Mixing extruders enable
  #
  - opt_enable MIXING_EXTRUDER
  - build_marlin
  
  #
  # Restore configuration and build in release
  #
  - restore_configs
  - build_marlin